### ISSUE TITLE
在node上面跑会报错

### ISSUE THREAD

**Issue by YeYongFen** [wookaoer/page-skeleton-core#1]
Debugger attached.
(node:14216) UnhandledPromiseRejectionWarning: ReferenceError: storagies is not defined
    at SkeletonCore.build (D:\SPACE\workspace\camapi - dev\node_modules\._page-skeleton-core@1.0.3-alpha@page-skeleton-core\src\skeletonCore.js:109:25)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:14216) UnhandledPromiseRejectionWarning: ReferenceError: storagies is not defined
    at SkeletonCore.build (D:\SPACE\workspace\camapi - dev\node_modules\._page-skeleton-core@1.0.3-alpha@page-skeleton-core\src\skeletonCore.js:109:25)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
warning.js:23
(node:14216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:23
(node:14216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Sessionh** [comment]
搜索storagies   删除相关代码就行 其实就是本地缓存而已

**Comment by wookaoer** [comment]
感谢提出问题，最近比较忙，才看到issue。已修复 谢谢！
